version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      expo:
        patterns: ["expo*", "@expo/*"]
      react-native:
        patterns: ["react-native*", "@react-native*"]
      dev-dependencies:
        dependency-type: development
