/**
 * Styles shared by the tournament detail screen and its tab panes.
 *
 * Lifted verbatim out of TournamentDetail so the panes can move into their own
 * files without each one forking the parts of this sheet it happens to touch.
 */

import { StyleSheet } from 'react-native';
import { spacingPixels, radiusPixels, secondary, accent } from '@rallia/design-system';

export const styles = StyleSheet.create({
  root: { flex: 1 },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacingPixels[6],
  },
  centeredText: { marginTop: spacingPixels[3], textAlign: 'center' },
  centeredSubtext: { marginTop: spacingPixels[2], textAlign: 'center' },
  retryButton: {
    marginTop: spacingPixels[4],
    paddingHorizontal: spacingPixels[5],
    paddingVertical: spacingPixels[3],
    borderRadius: radiusPixels.lg,
  },
  phaseDeadlineRow: {
    alignItems: 'center',
    marginBottom: spacingPixels[3],
  },
  phaseDeadlinePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[1],
    paddingHorizontal: spacingPixels[3],
    paddingVertical: spacingPixels[1.5],
    borderRadius: radiusPixels.full,
  },
  poolLaunchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingPixels[2],
    paddingVertical: spacingPixels[3],
    paddingHorizontal: spacingPixels[4],
    borderRadius: radiusPixels.lg,
    marginBottom: spacingPixels[4],
  },
  poolPhaseNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacingPixels[2],
    paddingVertical: spacingPixels[2.5],
    paddingHorizontal: spacingPixels[3],
    borderRadius: radiusPixels.lg,
    marginBottom: spacingPixels[4],
  },
  poolPhaseNoteText: {
    flex: 1,
  },
  knockoutTitle: {
    marginTop: spacingPixels[2],
  },
  myMatchDeadlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[1],
    marginTop: spacingPixels[1],
  },
  playersInviteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingPixels[2],
    paddingVertical: spacingPixels[3],
    paddingHorizontal: spacingPixels[4],
    borderRadius: radiusPixels.lg,
    marginBottom: spacingPixels[4],
  },
  heroFixed: {
    paddingBottom: spacingPixels[2],
  },
  heroBanner: {
    position: 'relative',
  },
  heroBannerTopRow: {
    position: 'absolute',
    top: spacingPixels[3],
    left: spacingPixels[4],
    right: spacingPixels[4],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacingPixels[2],
  },
  heroBannerBadges: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[1.5],
    marginLeft: 'auto',
    flexShrink: 1,
  },
  heroPrizeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[1],
    paddingHorizontal: spacingPixels[2.5],
    paddingVertical: spacingPixels[1],
    borderRadius: radiusPixels.full,
    backgroundColor: accent[300],
  },
  heroPointsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[1],
    paddingHorizontal: spacingPixels[2.5],
    paddingVertical: spacingPixels[1],
    borderRadius: radiusPixels.full,
    backgroundColor: 'rgba(255,255,255,0.94)',
  },
  heroScrim: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: spacingPixels[4],
    paddingTop: spacingPixels[3],
    paddingBottom: spacingPixels[3],
    gap: spacingPixels[1],
  },
  scrimText: {
    textShadowColor: 'rgba(0,0,0,0.55)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  heroChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacingPixels[2],
    paddingHorizontal: spacingPixels[4],
    paddingTop: spacingPixels[3],
  },
  heroChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[1.5],
    paddingHorizontal: spacingPixels[3],
    paddingVertical: spacingPixels[1.5],
    borderRadius: radiusPixels.full,
    borderWidth: 1,
    flexShrink: 1,
  },
  overviewActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[3],
    paddingHorizontal: spacingPixels[4],
    paddingVertical: spacingPixels[3.5],
  },
  overviewActionLabel: {
    flex: 1,
  },
  overviewActionBadge: {
    paddingHorizontal: spacingPixels[2],
    paddingVertical: spacingPixels[0.5],
    borderRadius: radiusPixels.full,
  },
  aboutBlock: {
    padding: spacingPixels[4],
    gap: spacingPixels[2],
  },
  aboutText: {
    lineHeight: 20,
  },
  aboutMore: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    alignSelf: 'flex-start',
  },
  overviewInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[3],
    paddingHorizontal: spacingPixels[4],
    paddingVertical: spacingPixels[3],
  },
  overviewInfoIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  overviewInfoTexts: {
    flex: 1,
    gap: 1,
  },
  playersPreviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[2],
    paddingHorizontal: spacingPixels[4],
    paddingVertical: spacingPixels[3],
  },
  playersPreviewAvatars: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  playersPreviewAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  playersPreviewAvatarOverlap: {
    marginLeft: -10,
  },
  playersPreviewAvatarImg: {
    width: '100%',
    height: '100%',
  },
  dockedBar: {
    paddingHorizontal: spacingPixels[4],
    paddingTop: spacingPixels[3],
    borderTopWidth: StyleSheet.hairlineWidth,
    gap: spacingPixels[3],
  },
  dockedBarHint: {
    textAlign: 'center',
    lineHeight: 16,
  },
  screenScroll: {
    flex: 1,
  },
  screenScrollContent: {
    flexGrow: 1,
  },
  tabBarSticky: {
    paddingTop: spacingPixels[2],
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  tabBarContent: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacingPixels[5],
    paddingHorizontal: spacingPixels[4],
  },
  tabItem: {
    alignItems: 'center',
    paddingTop: spacingPixels[2],
    gap: spacingPixels[2],
  },
  tabUnderline: {
    alignSelf: 'stretch',
    height: 2,
    borderRadius: 1,
  },
  tabContent: {
    padding: spacingPixels[4],
    paddingBottom: spacingPixels[8],
  },
  rulesCard: {
    paddingVertical: spacingPixels[1],
  },
  ruleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacingPixels[3],
    paddingHorizontal: spacingPixels[4],
    paddingVertical: spacingPixels[2.5],
  },
  ruleDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginTop: 7,
  },
  ruleText: {
    flex: 1,
    lineHeight: 20,
  },
  playersTabContent: {
    padding: spacingPixels[4],
    paddingBottom: spacingPixels[8],
  },
  pointsHero: {
    alignItems: 'center',
    gap: spacingPixels[1],
    padding: spacingPixels[5],
    borderRadius: radiusPixels.xl,
    borderWidth: 1,
  },
  pointsHeroIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacingPixels[1],
  },
  pointsHeroValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: spacingPixels[1.5],
  },
  pointsHeroCaption: {
    textAlign: 'center',
    lineHeight: 19,
  },
  pointsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[3],
    paddingHorizontal: spacingPixels[4],
    paddingVertical: spacingPixels[3],
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  pointsRowLast: {
    borderBottomWidth: 0,
  },
  pointsRowIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pointsRowLabel: {
    flex: 1,
  },
  pointsRowValue: {
    fontVariant: ['tabular-nums'],
  },
  pointsNoteRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacingPixels[3],
    paddingHorizontal: spacingPixels[4],
    paddingVertical: spacingPixels[3],
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  statusBadge: {
    paddingHorizontal: spacingPixels[3],
    paddingVertical: spacingPixels[1.5],
    borderRadius: radiusPixels.full,
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[2],
    paddingHorizontal: spacingPixels[3],
    paddingVertical: spacingPixels[1.5],
    borderRadius: radiusPixels.full,
  },
  liveIndicatorContainer: {
    width: 10,
    height: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveRing: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    shadowColor: secondary[500],
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
    elevation: 2,
  },
  stackedBlock: {
    padding: spacingPixels[4],
    gap: spacingPixels[1],
  },
  venueAddress: {
    lineHeight: 18,
  },
  infoRowLabel: {
    marginRight: spacingPixels[3],
  },
  infoRowValue: {
    flex: 1,
    textAlign: 'right',
  },
  stackedRow: {
    paddingHorizontal: spacingPixels[4],
    paddingVertical: spacingPixels[3],
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: spacingPixels[1],
  },
  stackedValue: {
    lineHeight: 20,
  },
  section: {
    marginBottom: spacingPixels[5],
  },
  sectionTitle: {
    marginBottom: spacingPixels[2],
    letterSpacing: 0.5,
  },
  card: {
    borderRadius: radiusPixels.lg,
    borderWidth: 1,
    overflow: 'hidden',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacingPixels[4],
    paddingVertical: spacingPixels[3],
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  stepperCard: {
    borderRadius: radiusPixels.lg,
    borderWidth: 1,
    paddingTop: spacingPixels[4],
    paddingBottom: spacingPixels[3],
    paddingHorizontal: spacingPixels[3],
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  stepperStep: {
    alignItems: 'center',
    gap: spacingPixels[1],
    width: 72,
  },
  stepperDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperConnector: {
    flex: 1,
    height: 2,
    borderRadius: 1,
    marginTop: 15,
    marginHorizontal: -spacingPixels[3],
  },
  ctaCard: {
    borderRadius: radiusPixels.xl,
    borderWidth: 1.5,
    padding: spacingPixels[4],
    gap: spacingPixels[3],
  },
  ctaCardHeader: {
    flexDirection: 'row',
    gap: spacingPixels[3],
  },
  ctaCardIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaCardTextBlock: {
    flex: 1,
    gap: spacingPixels[0.5],
  },
  ctaCardDescription: {
    lineHeight: 19,
  },
  statsCard: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderRadius: radiusPixels.lg,
    borderWidth: 1,
    paddingVertical: spacingPixels[3.5],
  },
  statSegment: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingHorizontal: spacingPixels[2],
  },
  statDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
    marginVertical: spacingPixels[0.5],
  },
  participantEmpty: {
    alignItems: 'center',
    paddingVertical: spacingPixels[8],
    paddingHorizontal: spacingPixels[5],
    gap: spacingPixels[2],
  },
  participantEmptyDisc: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacingPixels[1],
  },
  participantEmptyText: {
    textAlign: 'center',
  },
  participantEmptyStats: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    gap: spacingPixels[5],
    marginTop: spacingPixels[3],
    paddingTop: spacingPixels[4],
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  participantEmptyStat: {
    alignItems: 'center',
    gap: 2,
  },
  participantEmptyStatDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
  },
  pendingSection: {
    marginBottom: spacingPixels[4],
  },
  segmentBar: {
    marginBottom: spacingPixels[4],
  },
  myMatchCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[3],
    padding: spacingPixels[4],
    borderWidth: 1.5,
  },
  myMatchMain: {
    flex: 1,
    gap: spacingPixels[0.5],
  },
  myMatchStateText: {
    flex: 1,
  },
  roundChatBtn: {
    marginTop: spacingPixels[4],
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingPixels[2],
    paddingVertical: spacingPixels[4],
    borderRadius: radiusPixels.lg,
  },
  buttonDisabled: { opacity: 0.6 },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerMenuButton: {
    paddingHorizontal: spacingPixels[2],
    paddingVertical: spacingPixels[1],
  },
  menuBackdrop: {
    flex: 1,
  },
  menuCard: {
    position: 'absolute',
    right: spacingPixels[3],
    minWidth: 210,
    borderRadius: radiusPixels.xl,
    borderWidth: StyleSheet.hairlineWidth,
    paddingVertical: spacingPixels[1],
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[3],
    paddingHorizontal: spacingPixels[4],
    paddingVertical: spacingPixels[3.5],
  },
  bracketChipsRow: {
    flexDirection: 'row',
    gap: spacingPixels[2],
    paddingBottom: spacingPixels[3],
  },
  bracketChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[1],
    paddingHorizontal: spacingPixels[4],
    paddingVertical: spacingPixels[2],
    borderRadius: radiusPixels.full,
    borderWidth: 1,
  },
  bmRoundHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacingPixels[2],
    paddingHorizontal: spacingPixels[1],
  },
  bmProgressPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[1],
    paddingHorizontal: spacingPixels[2.5],
    paddingVertical: spacingPixels[1],
    borderRadius: radiusPixels.full,
  },
  bmPager: {
    minHeight: 1,
  },
  bracketPage: {
    paddingTop: spacingPixels[2],
    paddingBottom: spacingPixels[1],
    paddingHorizontal: spacingPixels[1],
  },
  bmPair: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginBottom: spacingPixels[5],
  },
  bmPairCards: {
    flex: 1,
    gap: spacingPixels[2],
  },
  bmConnector: {
    width: 48,
  },
  bmConnectorSpine: {
    position: 'absolute',
    left: 8,
    top: '25%',
    bottom: '25%',
    width: 2,
    borderRadius: 1,
  },
  bmConnectorArm: {
    position: 'absolute',
    left: 8,
    top: '50%',
    width: 16,
    height: 2,
    marginTop: -1,
  },
  bmConnectorBtn: {
    position: 'absolute',
    right: 0,
    top: '50%',
    width: 30,
    height: 30,
    marginTop: -15,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bmCard: {
    borderRadius: radiusPixels.xl,
    borderWidth: 1,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  bmCardPlayable: {
    borderWidth: 1.5,
  },
  bmStatusStrip: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingHorizontal: spacingPixels[3],
    paddingTop: spacingPixels[2],
  },
  bmStatusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[1],
    paddingHorizontal: spacingPixels[2],
    paddingVertical: spacingPixels[0.5],
    borderRadius: radiusPixels.full,
  },
  bmLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  bmRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[2],
    paddingVertical: spacingPixels[3],
    paddingHorizontal: spacingPixels[3],
  },
  bmRowCrown: {
    marginRight: -spacingPixels[1],
  },
  bmAvatarCluster: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bmAvatarClusterDim: {
    opacity: 0.6,
  },
  bmAvatar: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  bmAvatarStacked: {
    marginLeft: -8,
    borderWidth: 1.5,
  },
  bmAvatarImg: {
    width: '100%',
    height: '100%',
  },
  bmRowDivider: {
    height: StyleSheet.hairlineWidth,
    marginHorizontal: spacingPixels[3],
  },
  bmNameWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[1.5],
  },
  bmNameText: {
    flexShrink: 1,
  },
  bmScore: {
    minWidth: 18,
    textAlign: 'right',
  },
  bmSetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[2],
  },
  bmSetCell: {
    minWidth: 14,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  bmFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacingPixels[2],
    paddingHorizontal: spacingPixels[3],
    paddingVertical: spacingPixels[2.5],
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  bmFooterLabel: {
    flex: 1,
  },
  cancelledNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacingPixels[2],
    padding: spacingPixels[4],
    borderRadius: radiusPixels.lg,
    borderWidth: 1,
  },
  reasonInput: {
    borderWidth: 1,
    borderRadius: radiusPixels.md,
    paddingHorizontal: spacingPixels[3],
    paddingVertical: spacingPixels[3],
    fontSize: 15,
    minHeight: 72,
    marginBottom: spacingPixels[4],
    textAlignVertical: 'top',
  },
});
