/**
 * Shared shapes and helpers for the admin bug-report views.
 *
 * Bug reports are rows of `feedback` with category 'bug'. The reporter-typed
 * detail lives in the metadata JSON; subject/message are generated by the app.
 */

export const BUG_STATUSES = ['new', 'reviewed', 'in_progress', 'resolved', 'closed'] as const;
export const BUG_SEVERITIES = ['critical', 'major', 'minor'] as const;
export const FEEDBACK_MODULES = [
  'profile_settings',
  'match_features',
  'facilities',
  'player_directory',
  'groups_communities',
  'notifications',
  'performance',
  'other',
] as const;

export type BugStatus = (typeof BUG_STATUSES)[number];
export type BugSeverity = (typeof BUG_SEVERITIES)[number];

export interface AdminBugReport {
  id: string;
  category: string;
  module: string;
  subject: string;
  message: string;
  metadata: unknown;
  status: string;
  admin_notes: string | null;
  app_version: string | null;
  device_info: unknown;
  screenshot_urls: string[] | null;
  upvote_count: number;
  visibility: string;
  hidden_at: string | null;
  created_at: string;
  updated_at: string;
  reporter: { id: string; name: string; email: string | null } | null;
}

interface BugMetadata {
  severity?: string;
  steps_to_reproduce?: string;
  expected_vs_actual?: string;
}

export interface BugDeviceInfo {
  platform?: string;
  version?: string | number;
  trigger?: string;
}

export function bugMetadata(report: AdminBugReport): BugMetadata {
  return (report.metadata as BugMetadata | null) ?? {};
}

export function bugSeverity(report: AdminBugReport): BugSeverity | null {
  const severity = bugMetadata(report).severity;
  return BUG_SEVERITIES.includes(severity as BugSeverity) ? (severity as BugSeverity) : null;
}

/**
 * Bug subjects are auto-generated ("[major] Bug Report"), so the steps the
 * reporter typed are what actually identifies a row in the list.
 */
export function bugSummary(report: AdminBugReport): string {
  return (
    bugMetadata(report).steps_to_reproduce?.trim() ||
    report.message?.trim() ||
    report.subject?.trim() ||
    ''
  );
}

export const SEVERITY_BADGE: Record<BugSeverity, string> = {
  critical: 'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-400',
  major: 'bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-400',
  minor: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-950 dark:text-yellow-400',
};

export const STATUS_BADGE: Record<string, string> = {
  new: 'bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-400',
  reviewed: 'bg-violet-100 text-violet-700 dark:bg-violet-950 dark:text-violet-400',
  in_progress: 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-400',
  resolved: 'bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-400',
  closed: 'bg-gray-100 text-gray-600 dark:bg-gray-900 dark:text-gray-400',
};
