/**
 * close-matches Edge Function
 *
 * Automated match closure system that:
 * 1. Finds matches whose end time was more than 48 hours ago
 * 2. Detects mutual cancellations
 * 3. Aggregates feedback for each participant
 * 4. Creates reputation events based on aggregated feedback
 * 5. Marks matches as closed
 *
 * Triggered hourly by pg_cron
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

import { requireSecretApikey } from '../_shared/auth.ts';
import { reportHeartbeat } from '../_shared/heartbeat.ts';
import { captureEvent } from '../_shared/posthog.ts';

import {
  type MatchParticipant,
  type MatchFeedback,
  type AggregatedFeedback,
  type ReputationEventType,
  isMutualCancellation,
  getNoShowPlayerIds,
  aggregateFeedback,
  determineReputationEventTypes,
} from './closure-logic.ts';

// =============================================================================
// TYPES
// =============================================================================

interface MatchToClose {
  id: string;
  format: 'singles' | 'doubles';
}

/** Match-level fields needed for closure analytics (not returned by the closure RPC). */
interface MatchMeta {
  isAutoGenerated: boolean;
  createdBy: string | null;
  sportName: string | null;
}

interface ClosureResult {
  matchId: string;
  status: 'closed' | 'mutual_cancel' | 'error';
  error?: string;
  participantsProcessed?: number;
  reputationEventsCreated?: number;
}

// =============================================================================
// CONFIGURATION
// =============================================================================

const CUTOFF_HOURS = 48;
const BATCH_LIMIT = 100;

// Default impact values (fallback if DB config not available)
// Must match reputation_config seed data and specs/05-reputation/reputation-calculation.md
const DEFAULT_IMPACTS: Record<ReputationEventType, number> = {
  match_completed: 12,
  match_no_show: -50,
  match_on_time: 3,
  match_late: -10,
  review_received_5star: 10,
  review_received_4star: 5,
  review_received_3star: 0,
  review_received_2star: -5,
  review_received_1star: -10,
};

// Cache for reputation config
let reputationConfigCache: Map<string, number> | null = null;

// =============================================================================
// SUPABASE CLIENT
// =============================================================================

const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

const supabase = createClient(supabaseUrl, supabaseServiceKey);

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Fetch reputation config from database and cache it
 */
async function getReputationConfig(): Promise<Map<string, number>> {
  if (reputationConfigCache) {
    return reputationConfigCache;
  }

  const { data, error } = await supabase
    .from('reputation_config')
    .select('event_type, default_impact')
    .eq('is_active', true);

  if (error) {
    console.error('Failed to fetch reputation config:', error);
    // Return defaults as a map
    return new Map(Object.entries(DEFAULT_IMPACTS));
  }

  reputationConfigCache = new Map(
    (data || []).map((row: { event_type: string; default_impact: number }) => [
      row.event_type,
      row.default_impact,
    ])
  );

  return reputationConfigCache;
}

/**
 * Get impact value for an event type
 */
async function getImpactForEvent(eventType: ReputationEventType): Promise<number> {
  const config = await getReputationConfig();
  return config.get(eventType) ?? DEFAULT_IMPACTS[eventType] ?? 0;
}

/**
 * Get matches ready for closure (48+ hours since end time)
 */
async function getMatchesReadyForClosure(): Promise<MatchToClose[]> {
  const { data, error } = await supabase.rpc('get_matches_ready_for_closure', {
    cutoff_hours: CUTOFF_HOURS,
    batch_limit: BATCH_LIMIT,
  });

  if (error) {
    console.error('Failed to get matches ready for closure:', error);
    throw new Error(`Failed to query matches: ${error.message}`);
  }

  return (data || []) as MatchToClose[];
}

/**
 * Batch-fetch match-level metadata for closure analytics. Best-effort: on error
 * returns an empty map so the closure job is never blocked by analytics.
 */
async function getMatchMetas(matchIds: string[]): Promise<Map<string, MatchMeta>> {
  const metas = new Map<string, MatchMeta>();
  if (matchIds.length === 0) return metas;

  const { data, error } = await supabase
    .from('match')
    .select('id, is_auto_generated, created_by, sport:sport_id (name)')
    .in('id', matchIds);

  if (error) {
    console.warn('[close-matches] failed to fetch match metas for analytics:', error.message);
    return metas;
  }

  for (const row of data ?? []) {
    const sport = row.sport as { name?: string } | { name?: string }[] | null;
    const sportName = Array.isArray(sport) ? (sport[0]?.name ?? null) : (sport?.name ?? null);
    metas.set(row.id as string, {
      isAutoGenerated: (row.is_auto_generated as boolean | null) ?? false,
      createdBy: (row.created_by as string | null) ?? null,
      sportName,
    });
  }

  return metas;
}

/**
 * Get all participants for a match
 */
async function getMatchParticipants(matchId: string): Promise<MatchParticipant[]> {
  const { data, error } = await supabase
    .from('match_participant')
    .select('id, player_id, match_outcome, feedback_completed')
    .eq('match_id', matchId)
    .eq('status', 'joined');

  if (error) {
    throw new Error(`Failed to get participants: ${error.message}`);
  }

  return (data || []) as MatchParticipant[];
}

/**
 * Get all feedback records for a match
 */
async function getMatchFeedback(matchId: string): Promise<MatchFeedback[]> {
  const { data, error } = await supabase
    .from('match_feedback')
    .select('id, reviewer_id, opponent_id, showed_up, was_late, star_rating')
    .eq('match_id', matchId);

  if (error) {
    throw new Error(`Failed to get feedback: ${error.message}`);
  }

  return (data || []) as MatchFeedback[];
}

/**
 * Create reputation events for a participant based on aggregated feedback
 */
async function createReputationEvents(
  playerId: string,
  matchId: string,
  aggregated: AggregatedFeedback
): Promise<number> {
  const eventTypes = determineReputationEventTypes(aggregated);

  if (eventTypes.length === 0) {
    return 0;
  }

  // Build events with base_impact from config
  const events = await Promise.all(
    eventTypes.map(async eventType => {
      const baseImpact = await getImpactForEvent(eventType);
      return {
        player_id: playerId,
        event_type: eventType,
        base_impact: baseImpact,
        match_id: matchId,
        metadata: {
          source: 'closure_aggregation',
          ...(eventType.startsWith('review_received_') && aggregated.starRating
            ? { aggregated_rating: aggregated.starRating }
            : {}),
        },
        event_occurred_at: new Date().toISOString(),
      };
    })
  );

  // Insert all events
  const { error } = await supabase.from('reputation_event').insert(events);

  if (error) {
    console.error(`Failed to create reputation events for player ${playerId}:`, error);
    throw new Error(`Failed to create reputation events: ${error.message}`);
  }

  return events.length;
}

/**
 * Update match_participant with aggregated feedback
 */
async function updateParticipantAggregation(
  participantId: string,
  aggregated: AggregatedFeedback
): Promise<void> {
  const { error } = await supabase
    .from('match_participant')
    .update({
      showed_up: aggregated.showedUp,
      was_late: aggregated.wasLate,
      star_rating: aggregated.starRating,
      aggregated_at: new Date().toISOString(),
    })
    .eq('id', participantId);

  if (error) {
    throw new Error(`Failed to update participant: ${error.message}`);
  }
}

/**
 * Mark match as closed (with optional mutual cancellation flag)
 */
async function closeMatch(matchId: string, mutuallyCancelled: boolean = false): Promise<void> {
  const updateData: Record<string, unknown> = {
    closed_at: new Date().toISOString(),
  };

  if (mutuallyCancelled) {
    updateData.mutually_cancelled = true;
  }

  const { error } = await supabase.from('match').update(updateData).eq('id', matchId);

  if (error) {
    throw new Error(`Failed to close match: ${error.message}`);
  }
}

/**
 * Process a single match for closure
 */
async function processMatch(
  match: MatchToClose,
  meta: MatchMeta | undefined
): Promise<ClosureResult> {
  const matchId = match.id;

  try {
    // Get participants and feedback
    const [participants, feedback] = await Promise.all([
      getMatchParticipants(matchId),
      getMatchFeedback(matchId),
    ]);

    if (participants.length === 0) {
      await closeMatch(matchId);
      return {
        matchId,
        status: 'closed',
        participantsProcessed: 0,
        reputationEventsCreated: 0,
      };
    }

    // Check for mutual cancellation
    if (isMutualCancellation(participants)) {
      await closeMatch(matchId, true);
      return {
        matchId,
        status: 'mutual_cancel',
        participantsProcessed: participants.length,
        reputationEventsCreated: 0,
      };
    }

    // Determine which players are no-shows (for filtering their feedback)
    const noShowPlayerIds = getNoShowPlayerIds(feedback, participants);

    // Duplicate protection: check for existing closure-related reputation events for this match
    const { data: existingEvents } = await supabase
      .from('reputation_event')
      .select('player_id')
      .eq('match_id', matchId)
      .in('event_type', ['match_completed', 'match_no_show']);
    const playersWithEvents = new Set(existingEvents?.map(e => e.player_id) || []);

    // Aggregate feedback for every participant up front so we can judge whether
    // the match was *actually played* (mutual presence) before emitting the
    // per-player success signal.
    const aggregations = participants.map(participant => ({
      participant,
      aggregated: aggregateFeedback(participant.player_id, feedback, noShowPlayerIds),
    }));

    // A real, quality match requires at least two participants present — i.e.
    // the player AND at least one opponent showed up. A lone player who showed
    // up to a no-show did NOT play a match, and must not count toward the
    // play-goal north-star.
    const presentCount = aggregations.filter(a => a.aggregated.showedUp === true).length;
    const matchWasPlayed = presentCount >= 2;
    const allPresent = presentCount === aggregations.length;

    let totalReputationEvents = 0;

    for (const { participant, aggregated } of aggregations) {
      // Skip reputation event creation if already processed (idempotency),
      // but always update participant aggregation in case a previous run
      // created events but crashed before updating the participant record.
      if (!playersWithEvents.has(participant.player_id)) {
        const eventsCreated = await createReputationEvents(
          participant.player_id,
          matchId,
          aggregated
        );
        totalReputationEvents += eventsCreated;

        // Passive per-player success signal for analytics — a QUALITY match
        // played. Emitted only when (a) this participant showed up AND (b) the
        // match was genuinely played (>= 2 present, so a real opponent was
        // there). Mirrors the match_completed reputation event and is gated by
        // the same idempotency check, so it fires at most once per player/match.
        // Friction-free: no dependency on the player filing their own feedback.
        //
        // IMPORTANT: match quality is judged on the OTHER participants
        // (opponents), not on this player. What makes the match good *for him*
        // is whether his opponents showed up, were on time, and are well-rated —
        // his own showed_up only gates emission. (`aggregated` for participant X
        // is always feedback *about* X, so we read the opponents' own
        // aggregations here, never this player's.) Quality dimensions ride along
        // as props so the bar can be tuned in the analytics layer.
        if (aggregated.showedUp === true && matchWasPlayed) {
          const opponents = aggregations.filter(
            a => a.participant.player_id !== participant.player_id
          );
          const presentOpponents = opponents.filter(o => o.aggregated.showedUp === true);
          const opponentRatings = presentOpponents
            .map(o => o.aggregated.starRating)
            .filter((r): r is number => r !== null);
          const opponentsAvgRating = opponentRatings.length
            ? Math.round(
                (opponentRatings.reduce((s, r) => s + r, 0) / opponentRatings.length) * 10
              ) / 10
            : null;

          await captureEvent({
            distinctId: participant.player_id,
            event: 'match_played',
            properties: {
              match_id: matchId,
              is_auto_generated: meta?.isAutoGenerated ?? false,
              sport: meta?.sportName ?? null,
              format: match.format,
              present_count: presentCount,
              all_present: allPresent,
              // Quality of the OPPONENTS (the other participants), not this player:
              opponents_present: presentOpponents.length,
              opponents_all_present: presentOpponents.length === opponents.length,
              opponents_any_late: presentOpponents.some(o => o.aggregated.wasLate === true),
              opponents_avg_rating: opponentsAvgRating,
              opponents_min_rating: opponentRatings.length ? Math.min(...opponentRatings) : null,
            },
          });
        }
      }

      // Always update participant record — safe to re-run with same values
      await updateParticipantAggregation(participant.id, aggregated);
    }

    // Mark match as closed
    await closeMatch(matchId);

    return {
      matchId,
      status: 'closed',
      participantsProcessed: participants.length,
      reputationEventsCreated: totalReputationEvents,
    };
  } catch (error) {
    console.error(`Error processing match ${matchId}:`, error);
    return {
      matchId,
      status: 'error',
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

// =============================================================================
// MAIN HANDLER
// =============================================================================

Deno.serve(async req => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, {
      status: 204,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      },
    });
  }

  const authError = requireSecretApikey(req);
  if (authError) return authError;

  console.log('Starting match closure job...');
  const startTime = Date.now();

  try {
    // Get matches ready for closure
    const matches = await getMatchesReadyForClosure();
    console.log(`Found ${matches.length} matches ready for closure`);

    if (matches.length === 0) {
      await reportHeartbeat(Deno.env.get('BETTERSTACK_HEARTBEAT_CLOSE_MATCHES'));
      return new Response(
        JSON.stringify({
          success: true,
          message: 'No matches to close',
          matchesProcessed: 0,
          duration_ms: Date.now() - startTime,
        }),
        {
          status: 200,
          headers: { 'Content-Type': 'application/json' },
        }
      );
    }

    // Fetch match metadata once for analytics (auto-generated flag, host, sport).
    const metas = await getMatchMetas(matches.map(m => m.id));

    // Process each match
    const results: ClosureResult[] = [];
    for (const match of matches) {
      const meta = metas.get(match.id);
      const result = await processMatch(match, meta);
      results.push(result);
      console.log(`Match ${match.id}: ${result.status}`);

      // Terminal-state analytics: tracks the conversion outcome of every closed
      // match (including auto-generated ones that never filled, which client-side
      // events miss). Keyed to the host so auto vs organic matches are comparable.
      if (meta?.createdBy && (result.status === 'closed' || result.status === 'mutual_cancel')) {
        void captureEvent({
          distinctId: meta.createdBy,
          event: 'match_closed',
          properties: {
            match_id: match.id,
            is_auto_generated: meta.isAutoGenerated,
            sport: meta.sportName,
            format: match.format,
            status: result.status,
            joined_count: result.participantsProcessed ?? 0,
            reputation_events_created: result.reputationEventsCreated ?? 0,
          },
        });
      }
    }

    // Summarize results
    const summary = {
      success: true,
      matchesProcessed: results.length,
      closed: results.filter(r => r.status === 'closed').length,
      mutualCancel: results.filter(r => r.status === 'mutual_cancel').length,
      errors: results.filter(r => r.status === 'error').length,
      totalReputationEvents: results.reduce((sum, r) => sum + (r.reputationEventsCreated || 0), 0),
      duration_ms: Date.now() - startTime,
      results,
    };

    console.log(
      `Closure job complete: ${summary.closed} closed, ${summary.mutualCancel} mutual cancels, ${summary.errors} errors`
    );

    // Return error status if all matches failed
    const httpStatus = summary.errors === summary.matchesProcessed ? 500 : 200;

    if (httpStatus === 200) {
      await reportHeartbeat(Deno.env.get('BETTERSTACK_HEARTBEAT_CLOSE_MATCHES'));
    }

    return new Response(JSON.stringify(summary), {
      status: httpStatus,
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error('Match closure job failed:', error);

    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
        duration_ms: Date.now() - startTime,
      }),
      {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      }
    );
  }
});
