-- =============================================================================
-- Hardening pass on the UTM RPCs:
--   1) create_utm_campaign: force slug to lowercase BEFORE validating, so
--      `Friends_Family_2026` and `friends_family_2026` can't coexist.
--   2) set_profile_utm: lowercase utm_source / utm_medium before storing so a
--      hand-crafted `?utm_source=Instagram` doesn't fork from `instagram`.
--      utm_campaign and utm_content/term stay case-sensitive (campaigns are
--      generated by us via the link-builder; content is free-form).
--   3) get_utm_totals_with_comparison: single-query period-over-period totals
--      for the KPI cards (signups, matches_created, matches_played for both
--      the current window and the matched-length prior window).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1) create_utm_campaign — lowercase the slug
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.create_utm_campaign(text, text, text);

CREATE OR REPLACE FUNCTION public.create_utm_campaign(
  p_slug         text,
  p_display_name text,
  p_description  text DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_id UUID;
  v_slug TEXT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.admin WHERE id = auth.uid()) THEN
    RAISE EXCEPTION 'create_utm_campaign: caller is not an admin';
  END IF;

  IF p_slug IS NULL OR p_slug = '' THEN
    RAISE EXCEPTION 'create_utm_campaign: slug is required';
  END IF;

  -- Normalize to lowercase before validating + storing. Prevents the same
  -- campaign existing twice with different casing.
  v_slug := lower(p_slug);

  IF v_slug !~ '^[a-z0-9_]+$' THEN
    RAISE EXCEPTION 'create_utm_campaign: slug must be snake_case (a-z, 0-9, _)';
  END IF;

  IF p_display_name IS NULL OR p_display_name = '' THEN
    RAISE EXCEPTION 'create_utm_campaign: display_name is required';
  END IF;

  INSERT INTO public.utm_campaign (slug, display_name, description, created_by)
  VALUES (v_slug, p_display_name, NULLIF(p_description, ''), auth.uid())
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_utm_campaign(text, text, text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 2) set_profile_utm — lowercase source + medium on write
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.set_profile_utm(uuid, jsonb);

CREATE OR REPLACE FUNCTION public.set_profile_utm(
  p_player_id uuid,
  p_utm jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF auth.uid() IS NULL OR auth.uid() <> p_player_id THEN
    RAISE EXCEPTION 'set_profile_utm: caller does not own player_id';
  END IF;

  UPDATE public.profile
  SET
    -- Defend against case drift on source/medium — these are typed enums in
    -- code (`vocabulary.ts`); lowercase keeps the dashboard joined cleanly.
    utm_source   = COALESCE(utm_source,   lower(NULLIF(p_utm->>'utm_source',   ''))),
    utm_medium   = COALESCE(utm_medium,   lower(NULLIF(p_utm->>'utm_medium',   ''))),
    -- Campaign + content keep original casing — campaigns are minted by us,
    -- content is free-form variant labelling.
    utm_campaign = COALESCE(utm_campaign, NULLIF(p_utm->>'utm_campaign', '')),
    utm_content  = COALESCE(utm_content,  NULLIF(p_utm->>'utm_content',  '')),
    utm_term     = COALESCE(utm_term,     NULLIF(p_utm->>'utm_term',     ''))
  WHERE id = p_player_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.set_profile_utm(uuid, jsonb) TO authenticated;

-- Backfill: lowercase any existing utm_source / utm_medium so the period-over-
-- period comparison RPC below sees consistent values.
UPDATE public.profile
SET utm_source = lower(utm_source)
WHERE utm_source IS NOT NULL
  AND utm_source <> lower(utm_source);

UPDATE public.profile
SET utm_medium = lower(utm_medium)
WHERE utm_medium IS NOT NULL
  AND utm_medium <> lower(utm_medium);

-- ---------------------------------------------------------------------------
-- 3) get_utm_totals_with_comparison — current + previous period in one shot
--    Returns a SINGLE row. The current period is [now - p_days, now]; the
--    previous period is [now - 2*p_days, now - p_days] so the comparison is
--    apples-to-apples.
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.get_utm_totals_with_comparison(integer);

CREATE OR REPLACE FUNCTION public.get_utm_totals_with_comparison(p_days integer DEFAULT 7)
RETURNS TABLE(
  current_signups          bigint,
  current_matches_created  bigint,
  current_matches_played   bigint,
  previous_signups         bigint,
  previous_matches_created bigint,
  previous_matches_played  bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
#variable_conflict use_column
DECLARE
  v_days   integer    := GREATEST(p_days, 1);
  v_now    timestamptz := now();
  v_cur_start  timestamptz := v_now - make_interval(days => v_days);
  v_prev_start timestamptz := v_now - make_interval(days => v_days * 2);
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.admin WHERE id = auth.uid()) THEN
    RETURN;
  END IF;

  RETURN QUERY
  WITH cohort_current AS (
    SELECT p.id FROM public.profile p
    WHERE p.created_at >= v_cur_start
      AND p.utm_source IS NOT NULL
  ),
  cohort_previous AS (
    SELECT p.id FROM public.profile p
    WHERE p.created_at >= v_prev_start AND p.created_at < v_cur_start
      AND p.utm_source IS NOT NULL
  ),
  cur_matches AS (
    SELECT
      COUNT(*) FILTER (WHERE m.created_at >= v_cur_start) AS created,
      COUNT(DISTINCT mp.match_id) FILTER (
        WHERE mr.match_id IS NOT NULL AND mr.created_at >= v_cur_start
      ) AS played
    FROM cohort_current c
    LEFT JOIN public.match m ON m.created_by = c.id
    LEFT JOIN public.match_participant mp ON mp.player_id = c.id
    LEFT JOIN public.match_result mr ON mr.match_id = mp.match_id
  ),
  prev_matches AS (
    SELECT
      COUNT(*) FILTER (WHERE m.created_at >= v_prev_start AND m.created_at < v_cur_start) AS created,
      COUNT(DISTINCT mp.match_id) FILTER (
        WHERE mr.match_id IS NOT NULL
          AND mr.created_at >= v_prev_start
          AND mr.created_at < v_cur_start
      ) AS played
    FROM cohort_previous c
    LEFT JOIN public.match m ON m.created_by = c.id
    LEFT JOIN public.match_participant mp ON mp.player_id = c.id
    LEFT JOIN public.match_result mr ON mr.match_id = mp.match_id
  )
  SELECT
    (SELECT count(*)::bigint FROM cohort_current),
    COALESCE((SELECT created FROM cur_matches), 0)::bigint,
    COALESCE((SELECT played  FROM cur_matches), 0)::bigint,
    (SELECT count(*)::bigint FROM cohort_previous),
    COALESCE((SELECT created FROM prev_matches), 0)::bigint,
    COALESCE((SELECT played  FROM prev_matches), 0)::bigint;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_utm_totals_with_comparison(integer) TO authenticated;
