-- Montreal facility/court data corrections, from official sources (montreal.ca + demerged-city sites),
-- researched 2026-07-23. Full source report: montreal-tennis-facilities.md (session artifact).
-- All rows matched by facility.slug (unique, shared across environments); UUIDs differ per env.
-- Data-only migration: no schema changes. Courts are never deleted, only deactivated.

-- 1. Identity & address hygiene ------------------------------------------------
update facility set name = 'Parc De La Vérendrye' where slug = 'parcde-la-verendrye-montreal';
update facility set address = '11750, rue La Valinière' where slug = 'parc-dollard-morin-montreal';
update facility set address = '11440, avenue Éthier' where slug = 'parc-sauve-montreal';
update facility set address = '11345, avenue Pelletier' where slug = 'parc-ecole-calixa-lavallee-montreal';
update facility set address = '260 Spring Garden St' where slug = 'coolbrooke-park-mooxhxwt';
update facility set city = 'Dollard-Des Ormeaux', timezone = coalesce(timezone, 'America/Toronto') where slug = 'parc-westwood-mooy2bm5';
update facility set postal_code = trim(postal_code) where slug in ('gymnase-de-l-ecole-calixa-lavallee-montreal','coolbrooke-park-mooxhxwt','parc-terry-fox-mooxtk4q','parc-westwood-mooy2bm5') and postal_code is not null;
-- Demerged cities: these facilities are not in the city of Montreal
update facility set city = 'Westmount' where slug in ('parc-devon-montreal','parc-king-george-montreal','parc-stayner-montreal','parc-westmount-montreal','terrains-de-tennis-du-terrain-d-athletisme-de-westmount-wag-montreal');
update facility set city = 'Hampstead' where slug = 'parc-hampstead-montreal';
update facility set city = 'Côte Saint-Luc' where slug in ('parc-caldwell-montreal','parc-rembrandt-montreal');
update facility set city = 'Dorval' where slug = 'club-municipal-de-tennis-de-dorval-montreal';

-- 2. Access model --------------------------------------------------------------
update facility set is_first_come_first_serve = true where slug in ('parc-george-springate-montreal','coolbrooke-park-mooxhxwt','parc-terry-fox-mooxtk4q','parc-westwood-mooy2bm5','parc-goncourt-montreal','parc-devon-montreal','parc-king-george-montreal','parc-stayner-montreal','parc-westmount-montreal','terrains-de-tennis-du-terrain-d-athletisme-de-westmount-wag-montreal','parc-saint-viateur-montreal');
update facility set is_first_come_first_serve = false where slug in ('parc-ottawa-montreal');
update facility set membership_required = true where slug in ('centre-de-tennis-cavelier-montreal','parc-delorme-montreal','parc-hebert-lasalle-montreal','parc-woodland-montreal','club-municipal-de-tennis-de-dorval-montreal','parc-joyce-montreal','parc-saint-viateur-montreal','parc-f-x-garneau-montreal','parc-devon-montreal','parc-king-george-montreal','parc-stayner-montreal','parc-westmount-montreal','terrains-de-tennis-du-terrain-d-athletisme-de-westmount-wag-montreal','parc-hampstead-montreal');

-- 3. Closures ------------------------------------------------------------------
-- Parc François-Perrault: permanently closed per montreal.ca
update facility set is_active = false where slug = 'parc-francois-perrault-montreal';
update court set is_active = false, availability_status = 'closed', notes = 'Permanently closed per montreal.ca (2026-07)'
  where facility_id in (select id from facility where slug = 'parc-francois-perrault-montreal');
-- Temporary closures: keep courts active but mark maintenance
update court set availability_status = 'maintenance', notes = 'Clay courts preventively closed until further notice (montreal.ca, 2026-07)'
  where facility_id in (select id from facility where slug = 'parc-de-roxboro-montreal');
update court set availability_status = 'maintenance', notes = 'Closed for construction, summer 2026 (montreal.ca)'
  where facility_id in (select id from facility where slug = 'parc-george-vernot-montreal');
update court set availability_status = 'maintenance', notes = 'Temporarily closed, work ongoing (montreal.ca, 2026-07)'
  where facility_id in (select id from facility where slug = 'parc-wilfrid-bastien-montreal');
update court set availability_status = 'maintenance', notes = 'Clay courts temporarily closed (montreal.ca, 2026-07); operated by private Club de tennis Woodland'
  where facility_id in (select id from facility where slug = 'parc-woodland-montreal');

-- 4. Court data fixes ----------------------------------------------------------
-- Stade IGA covered clay courts were stored as hard
update court set surface_type = 'clay'
  where facility_id in (select id from facility where slug = 'parc-jarry-stade-iga-terrains-de-tennis-interieurs-terre-battue-montreal');
-- Dorval: official pages list 8 clay tennis courts and no pickleball at the club
update court set is_active = false, notes = 'No pickleball at the club per official pages (2026-07); deactivated pending verification'
  where facility_id in (select id from facility where slug = 'club-municipal-de-tennis-de-dorval-montreal') and court_number = 9;
delete from facility_sport fs using facility f, sport s
  where fs.facility_id = f.id and fs.sport_id = s.id
    and f.slug = 'club-municipal-de-tennis-de-dorval-montreal' and s.name = 'pickleball';
-- Warren-Allmand: official page lists 3 pickleball courts, DB had 2
insert into court (facility_id, name, court_number, indoor, lighting, is_active, availability_status)
select f.id, 'Court 14', 14, false, c13.lighting, true, 'available'
from facility f join court c13 on c13.facility_id = f.id and c13.court_number = 13
where f.slug = 'parc-warren-allmand-montreal'
  and not exists (select 1 from court c where c.facility_id = f.id and c.court_number = 14);
insert into court_sport (court_id, sport_id)
select c.id, s.id from court c
join facility f on f.id = c.facility_id and f.slug = 'parc-warren-allmand-montreal'
cross join sport s where s.name = 'pickleball' and c.court_number = 14
  and not exists (select 1 from court_sport cs where cs.court_id = c.id and cs.sport_id = s.id);

-- 5. Official info per facility (merged into attributes.official_info) ----------
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Laurent","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-alexis-nihon","page_en":"https://montreal.ca/en/places/parc-alexis-nihon-outdoor-tennis-courts","booking":"Loisirs Montreal online, up to 72h ahead, free, valid leisure/library card, 1 reservation per day","fees":"Free","season":"Daily 9:00-22:00, weather permitting"}}'::jsonb where slug = 'parc-alexis-nihon-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Laurent","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-cousineau","page_en":"https://montreal.ca/en/places/parc-cousineau-outdoor-tennis-courts","phone":"514 855-6118","booking":"Loisirs Montreal online, up to 72h ahead, free, valid leisure/library card, 1 reservation per day","fees":"Free"}}'::jsonb where slug = 'parc-cousineau-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Laurent","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-gohier","page_en":"https://montreal.ca/en/places/parc-gohier-outdoor-tennis-courts","booking":"Loisirs Montreal online, up to 72h ahead, free, valid leisure/library card, 1 reservation per day","fees":"Free","season":"Daily 9:00-22:00, weather permitting"}}'::jsonb where slug = 'parc-gohier-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Laurent","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-hartenstein","page_en":"https://montreal.ca/en/places/parc-hartenstein-outdoor-tennis-courts","booking":"Loisirs Montreal online, up to 72h ahead, free, valid leisure/library card, 1 reservation per day","fees":"Free","season":"Daily 9:00-22:00, weather permitting","notes":"1 of 2 courts closed for renovation (2026-07)"}}'::jsonb where slug = 'parc-hartenstein-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Laurent","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-marcel-laurin","page_en":"https://montreal.ca/en/places/parc-marcel-laurin-outdoor-tennis-courts","phone":"514 956-2596","booking":"Loisirs Montreal online, up to 72h ahead, free, valid leisure/library card, 1 reservation per day","fees":"Free","season":"Daily 9:00-22:00, weather permitting"}}'::jsonb where slug = 'parc-marcel-laurin-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Laurent","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-noel-sud","page_en":"https://montreal.ca/en/places/parc-noel-sud-outdoor-tennis-courts","booking":"Loisirs Montreal online, up to 72h ahead, free, valid leisure/library card, 1 reservation per day","fees":"Free; paid lessons offered","season":"Daily 9:00-22:00, weather permitting"}}'::jsonb where slug = 'parc-noel-sud-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Laurent","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-painter","page_en":"https://montreal.ca/en/places/parc-painter-outdoor-tennis-courts","booking":"Loisirs Montreal online, up to 72h ahead, free, valid leisure/library card, 1 reservation per day","fees":"Free","season":"Daily 9:00-22:00, weather permitting"}}'::jsonb where slug = 'parc-painter-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Laurent","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-philippe-laheurte","page_en":"https://montreal.ca/en/places/parc-philippe-laheurte-tennis-court","booking":"Loisirs Montreal online, up to 72h ahead, free, valid leisure/library card, 1 reservation per day (bookable site confirmed on loisirs.montreal.ca)","fees":"Free","season":"Daily 9:00-22:00, weather permitting"}}'::jsonb where slug = 'parc-philippe-laheurte-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Laurent","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-saint-laurent-arr-saint-laurent","page_en":"https://montreal.ca/en/places/parc-saint-laurent-arr-saint-laurent-outdoor-tennis-courts","booking":"Loisirs Montreal online, up to 72h ahead, free, valid leisure/library card, 1 reservation per day","fees":"Free","season":"Daily 9:00-22:00, weather permitting"}}'::jsonb where slug = 'parc-saint-laurent-arr-saint-laurent-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Laurent","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-marlborough","page_en":"https://montreal.ca/en/places/parc-marlborough-outdoor-tennis-courts","booking":"Loisirs Montreal online, up to 72h ahead, free, valid leisure/library card, 1 reservation per day","fees":"Free","season":"Daily 9:00-22:00, weather permitting","notes":"montreal.ca classifies this park under Saint-Laurent, not Cartierville"}}'::jsonb where slug = 'parc-marlborough-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Ahuntsic-Cartierville","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-camille","page_en":"https://montreal.ca/en/places/parc-camille-outdoor-tennis-court","booking":"Free play, no reservation; leave after 1h when others wait","fees":"Free","season":"Daily 6:00-23:00"}}'::jsonb where slug = 'parc-camille-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Ahuntsic-Cartierville","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-marcelin-wilson","page_en":"https://montreal.ca/en/places/parc-marcelin-wilson-outdoor-tennis-courts","booking":"Loisirs Montreal online mandatory during summer windows, up to 24h ahead; free play otherwise","fees":"Free","season":"Daily 6:00-23:00"}}'::jsonb where slug = 'parc-marcelin-wilson-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Ahuntsic-Cartierville","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-nicolas-viel","page_en":"https://montreal.ca/en/places/parc-nicolas-viel-tennis-courts","phone":"311","booking":"Loisirs Montreal online mandatory, up to 24h ahead","fees":"Free","season":"Daily 6:00-23:00, ~mid-April to early November"}}'::jsonb where slug = 'parc-nicolas-viel-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Ahuntsic-Cartierville","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-exterieurs-du-complexe-sportif-claude-robillard","page_en":"https://montreal.ca/en/places/complexe-sportif-claude-robillard-outdoor-tennis-courts","phone":"514 872-1144","email":"cscr@montreal.ca","booking":"Loisirs Montreal or phone; window opens 48h before the desired hour; max 2h","fees":"Free Apr 21-Jun 26 and after Sep 5; peak Jun 27-Sep 4: $12/h youth-senior res, $16/h adult res, $25/h non-res","season":"Jun 27 - Oct 11, 2026, daily 8:00-23:00"}}'::jsonb where slug = 'complexe-sportif-claude-robillard-terrains-exterieurs-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Ahuntsic-Cartierville","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-interieurs-du-complexe-sportif-claude-robillard","page_en":"https://montreal.ca/en/places/complexe-sportif-claude-robillard-indoor-tennis-courts","phone":"514 872-6900 opt 0","email":"cscr@montreal.ca","booking":"Loisirs Montreal, 48h window","fees":"Res $14.50/h (10-17, 60+), $24.50/h (18-59); non-res $25-45/h","season":"Year-round","notes":"2 of 4 courts closed for construction (2026-07)"}}'::jsonb where slug = 'complexe-sportif-claude-robillard-terrains-interieurs-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Le Plateau-Mont-Royal","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-jeanne-mance","page_en":"https://montreal.ca/en/places/parc-jeanne-mance-tennis-courts","phone":"514 872-5520","email":"reservationterrainsport_plateau@montreal.ca","booking":"Paid reservation via Loisirs Montreal (48h) or phone after 9:15 next-day only; pay 10 min before slot; free play daily 8:00-9:00 + late evenings","fees":"2026 residents $6 (17-) / $12 (18-64) / $7.25 (65+); non-res $15.50; debit only on site","season":"Apr 24 - Oct 13, 2026, daily 8:00-23:00","notes":"On-site booth with attendant; cancellations >=3h ahead, credit only"}}'::jsonb where slug = 'parc-jeanne-mance-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Le Plateau-Mont-Royal","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-et-de-pickleball-du-parc-la-fontaine","page_en":"https://montreal.ca/en/places/parc-la-fontaine-tennis-courts","phone":"514 872-3626","email":"reservationterrainsport_plateau@montreal.ca","booking":"Paid reservation via Loisirs Montreal (48h) or phone next-day only; free play daily 8:00-9:00 + late evenings","fees":"2026 residents $6 / $12 / $7.25; non-res $15.50; debit only on site","season":"Apr 24 - Oct 13, 2026, daily 8:00-23:00","notes":"14 tennis (7 clay-type, 7 fast) + up to 6 pickleball"}}'::jsonb where slug = 'parc-la-fontaine-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Ville-Marie","checked_at":"2026-07-23","source":"official website","page_en":"https://montreal.ca/en/places/parc-mederic-martin-tennis-courts","phone":"514 714-2144","booking":"Not on Loisirs Montreal; reserve 48h ahead by phone or on site with attendant; max 2h; pay in person 10 min before slot","fees":"$10/h or 6-session booklet $50 (borough page 2026)"}}'::jsonb where slug = 'parc-mederic-martin-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Outremont","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-joyce","page_en":"https://montreal.ca/en/places/park-joyce-outdoor-tennis-courts","phone":"514 495-6211","email":"cci@montreal.ca","booking":"Outremont subscription or day pass mandatory; club hours reserved via Balle Jaune (Club de tennis Joyce)","fees":"2026 season (club): $254.50 individual, $479.25 family, $229.25 student; sold on Loisirs Montreal","season":"From May 16, 2026, weather permitting; clay closes when wet"}}'::jsonb where slug = 'parc-joyce-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Outremont","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-et-de-pickleball-du-parc-oakwood","booking":"Free at all times, no reservation, no subscription","fees":"Free","season":"Daily 7:00-22:00; from May 16, 2026"}}'::jsonb where slug = 'parc-oakwood-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Outremont","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-saint-viateur","page_en":"https://montreal.ca/en/places/parc-saint-viateur-outdoor-tennis-courts","phone":"514 495-6211","email":"cci@montreal.ca","booking":"Subscription or day pass mandatory; first-come-first-served hourly blocks (no per-slot reservation)","fees":"2026 season (public): $183 individual, $293 family, $164.75 student","season":"From May 16, 2026; Mon-Fri 7:00-23:00, Sat-Sun 8:00-22:00; clay closes when wet"}}'::jsonb where slug = 'parc-saint-viateur-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Outremont","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-f-x-garneau","phone":"514 495-6211","email":"loisirs.outremont@montreal.ca","booking":"Subscription mandatory + reservation via Loisirs Montreal up to 48h ahead, 55 min slots, 1/day","fees":"Same public subscription grid as Saint-Viateur","season":"From May 16, 2026; Mon-Fri 7:00-23:00, Sat-Sun 8:00-22:00","notes":"Located in Outremont (place Elmwood), not an east-end borough"}}'::jsonb where slug = 'parc-f-x-garneau-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Cote-des-Neiges-Notre-Dame-de-Grace","checked_at":"2026-07-23","source":"official website","page_en":"https://montreal.ca/en/places/parc-martin-luther-king-tennis-and-pickleball-courts","phone":"514 872-1122","email":"tenniscdn-ndg@montreal.ca","booking":"Loisirs Montreal online up to 72h or phone/in-person 48h; free-play windows weekday middays + weekend evenings; cancellations by email only >=4h","fees":"Residents 1h: $3.70-$11.10 by age/time; pickleball cheaper; free after Oct 14","season":"Jun 20 - Oct 12: Mon-Fri 8:00-22:00, Sat-Sun 9:00-21:00; fall to Nov 8"}}'::jsonb where slug = 'parc-martin-luther-king-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Cote-des-Neiges-Notre-Dame-de-Grace","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-et-de-pickleball-du-parc-warren-allmand","page_en":"https://montreal.ca/en/places/parc-warren-allmand-tennis-and-pickleball-courts","phone":"514 872-1123","email":"tenniscdn-ndg@montreal.ca","booking":"Loisirs Montreal online up to 72h or phone/in-person 48h; free-play windows; email-only cancellations >=4h","fees":"Residents 1h $3.90-$11.10; non-res $16.70; booklets 6/$46.50, 12/$85.90","season":"Apr 9 - Nov 8, 2026 in three schedule blocks","notes":"Official page lists 11 tennis + 3 pickleball"}}'::jsonb where slug = 'parc-warren-allmand-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Le Sud-Ouest","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-jacques-viger","phone":"514 690-1398","booking":"Free open play daytime/weekend-evening windows; evenings Mon-Fri 17:00-22:00 and Sat-Sun 9:00-14:00 managed by ATSOM (phone, fees apply)","fees":"Free during open hours; ATSOM fees for reserved periods","season":"Apr 3 - Oct 16, 2026","notes":"Manual push-button lighting, ~60 min per activation"}}'::jsonb where slug = 'parc-jacques-viger-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Le Sud-Ouest","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-saint-jean-de-matha","page_en":"https://montreal.ca/en/places/parc-saint-jean-de-matha-tennis-courts","phone":"514 690-1398 / ATSOM 514 690-1320","booking":"Free open play daytime/weekend-evening windows; evenings Mon-Fri 17:00-22:00 and Sat-Sun 9:00-14:00 managed by ATSOM (phone, fees apply)","fees":"Free during open hours; ATSOM fees for reserved periods","season":"May 2 - Oct 16, 2026"}}'::jsonb where slug = 'parc-saint-jean-de-matha-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Le Sud-Ouest","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-de-la-verendrye","phone":"514 690-1398","booking":"Free open play daytime/weekend-evening windows; evenings Mon-Fri 17:00-22:00 and Sat-Sun 9:00-14:00 managed by ATSOM (phone, fees apply)","fees":"Free during open hours; ATSOM fees for reserved periods","season":"May 2 - Oct 16, 2026; lit May 2 - Oct 31","notes":"9 standard courts + 4 mini-tennis courts (mini-tennis, not pickleball, per official page)"}}'::jsonb where slug = 'parcde-la-verendrye-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Le Sud-Ouest","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-de-la-place-roland-proulx","page_en":"https://montreal.ca/en/places/place-roland-proulx-tennis-courts","phone":"514 690-1320","booking":"Free open play daytime/weekend-evening windows; evenings Mon-Fri 17:00-22:00 and Sat-Sun 9:00-14:00 managed by ATSOM (phone, fees apply)","fees":"Free during open hours; ATSOM fees for reserved periods","season":"Apr 3 - Oct 16, 2026; lit May 2 - Oct 31"}}'::jsonb where slug = 'place-roland-proulx-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Verdun","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-arthur-therrien","page_en":"https://montreal.ca/en/places/parc-arthur-therrien-outdoor-tennis-courts","phone":"514 765-7270","email":"verdun.cce@montreal.ca","booking":"Loisirs Montreal online; seasonal subscription mandatory; window opens 2 days + 2h ahead; 1h per reservation; free play daily 7:00-9:00","fees":"Season pass $46 resident / $69 non-resident (Apr 15 - Nov 16, 2026)","season":"Daily 7:00-22:00"}}'::jsonb where slug = 'parc-arthur-therrien-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Verdun (Ile-des-Soeurs)","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-et-de-pickleball-du-parc-dan-hanganu-elgar","page_en":"https://montreal.ca/en/places/parc-dan-hanganu-elgar-outdoor-tennis-courts","phone":"514 765-7270","email":"verdun.cce@montreal.ca","booking":"Loisirs Montreal online; seasonal subscription mandatory; window opens 2 days + 2h ahead; 1h per reservation; free play daily 7:00-9:00","fees":"Season pass $46 resident / $69 non-resident (Apr 15 - Nov 16, 2026)","season":"Daily 7:00-22:00","notes":"Pickleball courts split by level: 3a-3b under 3.0, 4a-4b over 3.0"}}'::jsonb where slug = 'parc-dan-hanganu-elgar-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Verdun (Ile-des-Soeurs)","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-de-la-fontaine","page_en":"https://montreal.ca/en/places/parc-de-la-fontaine-outdoor-tennis-courts","phone":"514 765-7270","email":"verdun.cce@montreal.ca","booking":"Loisirs Montreal online; seasonal subscription mandatory; window opens 2 days + 2h ahead; 1h per reservation; free play daily 7:00-9:00","fees":"Season pass $46 resident / $69 non-resident (Apr 15 - Nov 16, 2026)","season":"Daily 7:00-22:00","notes":"Hosts the Jeu, set et match borough league"}}'::jsonb where slug = 'parc-de-la-fontaine-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Verdun","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-et-de-pickleball-du-parc-wilson","page_en":"https://montreal.ca/en/places/parc-wilson-outdoor-tennis-courts","phone":"514 765-7270","email":"verdun.cce@montreal.ca","booking":"Loisirs Montreal online; seasonal subscription mandatory; window opens 2 days + 2h ahead; 1h per reservation; free play daily 7:00-9:00","fees":"Season pass $46 resident / $69 non-resident (Apr 15 - Nov 16, 2026)","season":"Daily 7:00-22:00","notes":"Free pickleball drop-in Mondays 9:00-12:00 on courts 1-2 (tennis nets)"}}'::jsonb where slug = 'parc-wilson-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Verdun (Crawford Park)","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-de-la-reine-elizabeth","page_en":"https://montreal.ca/en/places/parc-de-la-reine-elizabeth-outdoor-tennis-courts","phone":"514 765-7270","email":"verdun.cce@montreal.ca","booking":"Loisirs Montreal online; seasonal subscription mandatory; window opens 2 days + 2h ahead; 1h per reservation; free play daily 7:00-9:00","fees":"Season pass $46 resident / $69 non-resident (Apr 15 - Nov 16, 2026)","season":"Daily 7:00-22:00","notes":"Borough is Verdun (H4H, Crawford Park), not Le Sud-Ouest"}}'::jsonb where slug = 'parc-de-la-reine-elizabeth-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Verdun","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/parc-woodland","phone":"514 765-7253","booking":"Members-only private Club de tennis Woodland; booking via tennisenligne.ca; guests $10/day","fees":"Club membership; amounts not published","season":"May - October","notes":"Clay courts temporarily closed per montreal.ca (2026-07)","operator":"Club de tennis Woodland (private, clay, est. 1923)"}}'::jsonb where slug = 'parc-woodland-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"LaSalle","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/centre-de-tennis-cavelier","page_en":"https://montreal.ca/en/places/centre-de-tennis-cavelier","phone":"514 367-6445","booking":"Membership model; on-site/phone reservations, members can book 48h ahead; not on Loisirs Montreal","fees":"2026 season with Acces-services LaSalle card: $48 child/student, $74 adult, $58.25 50+, $159.25 family; without card higher; day rental $8.25/h with card, $12.25/h without","season":"May 6 - Sep 1: Mon-Fri 9:00-22:00, Sat-Sun 9:00-21:00; fall schedule after"}}'::jsonb where slug = 'centre-de-tennis-cavelier-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"LaSalle","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/court-de-tennis-du-parc-hebert-lasalle","page_en":"https://montreal.ca/en/places/parc-hebert-outdoor-tennis-courts","phone":"514 367-3486 (in season)","email":"clubdetennislasalle68e@gmail.com","booking":"Members of Club de tennis LaSalle only","fees":"Set by the club","season":"Daily 7:00-23:00","operator":"Club de tennis LaSalle"}}'::jsonb where slug = 'parc-hebert-lasalle-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"LaSalle","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/court-de-tennis-du-parc-hayward","page_en":"https://montreal.ca/en/places/parc-hayward-outdoor-tennis-courts","booking":"Free, no reservation, first-come-first-served; 45 min max per game; no queuing at courts","fees":"Free","season":"Daily 7:00-23:00, weather permitting","notes":"Page showed a temporary-closure banner on 2026-07-23 (possibly stale)"}}'::jsonb where slug = 'parc-hayward-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"LaSalle","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-lacharite","booking":"Free, no reservation, first-come-first-served; 45 min max per game; no queuing at courts","fees":"Free","season":"Daily 7:00-23:00, weather permitting"}}'::jsonb where slug = 'parc-lacharite-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"LaSalle","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/court-de-tennis-du-parc-lefebvre","booking":"Free, no reservation, first-come-first-served; 45 min max per game; no queuing at courts; pickleball free with on-site equipment lending","fees":"Free","season":"Tennis daily 7:00-23:00; pickleball 7:00-20:00","notes":"Official pages list 1 tennis + 6 dedicated pickleball; DB has 3 tennis"}}'::jsonb where slug = 'parc-lefebvre-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"LaSalle","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-leroux","booking":"Free, no reservation, first-come-first-served; 45 min max per game; no queuing at courts","fees":"Free","season":"Daily 7:00-23:00, weather permitting"}}'::jsonb where slug = 'parc-leroux-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"LaSalle","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/court-de-tennis-du-parc-menard-lasalle","booking":"Free, no reservation, first-come-first-served; 45 min max per game; no queuing at courts","fees":"Free","season":"Daily 7:00-23:00, weather permitting"}}'::jsonb where slug = 'parc-menard-lasalle-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"LaSalle","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-mohawk","page_en":"https://montreal.ca/en/places/parc-mohawk","booking":"Free, no reservation, first-come-first-served; 45 min max per game; no queuing at courts","fees":"Free","season":"Daily 7:00-23:00, weather permitting"}}'::jsonb where slug = 'parc-mohawk-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"LaSalle","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/court-de-tennis-du-parc-ouellette","booking":"Free, no reservation, first-come-first-served; 45 min max per game; no queuing at courts","fees":"Free","season":"Daily 7:00-23:00, weather permitting"}}'::jsonb where slug = 'parc-ouellette-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"LaSalle","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/court-de-tennis-du-parc-riverside","page_en":"https://montreal.ca/en/places/parc-riverside-outdoor-tennis-courts","booking":"Free, no reservation, first-come-first-served; 45 min max per game; no queuing at courts","fees":"Free","season":"Daily 7:00-23:00, weather permitting"}}'::jsonb where slug = 'parc-riverside-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Lachine","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/court-de-tennis-du-parc-carignan","phone":"514 639-2248","email":"loisirslachine@montreal.ca","booking":"Free, no reservation","fees":"Free","season":"Apr 15 - Oct 31, daily 8:00-22:30, weather permitting"}}'::jsonb where slug = 'parc-carignan-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Lachine","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/court-de-tennis-du-parc-dixie","email":"loisirslachine@montreal.ca","booking":"Free, no reservation","fees":"Free","season":"Apr 15 - Oct 31, daily 8:00-22:30, weather permitting"}}'::jsonb where slug = 'parc-dixie-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Lachine","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/court-de-tennis-du-parc-kirkland","email":"loisirslachine@montreal.ca","booking":"Free, no reservation; courts lined for pickleball","fees":"Free","season":"Apr 15 - Oct 31, daily 8:00-22:30, weather permitting"}}'::jsonb where slug = 'parc-kirkland-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Lachine","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/centre-de-tennis-du-parc-lasalle","phone":"438 865-3364","email":"loisirslachine@montreal.ca","booking":"Free courts, reservable on loisirs.montreal.ca 2 days ahead from 9:00, or same-day at chalet/phone; paid pickleball options","fees":"Court reservation free; paid pickleball season pass $91.98 res / $196.81 non-res; single 60-min $6.90 / $12.65","season":"Peak: daily 9:00-22:00","notes":"Centre de tennis du parc LaSalle; in Lachine borough despite the name; free equipment lending at chalet"}}'::jsonb where slug = 'parc-lasalle-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-alexander","page_en":"https://montreal.ca/en/places/parc-alexander-outdoor-tennis-courts","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Daily 8:00-23:00"}}'::jsonb where slug = 'parc-alexander-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-brook","page_en":"https://montreal.ca/en/places/parc-brook-outdoor-tennis-courts","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Daily 8:00-23:00"}}'::jsonb where slug = 'parc-brook-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-da-ma-baie","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Daily 8:00-23:00"}}'::jsonb where slug = 'parc-d-a-ma-baie-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-de-roxboro","page_en":"https://montreal.ca/en/places/parc-de-roxboro-outdoor-tennis-courts","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Apr 15 - Oct 31, daily 8:00-23:00","notes":"Clay courts preventively CLOSED until further notice (2026-07)"}}'::jsonb where slug = 'parc-de-roxboro-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-duval","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Daily 8:00-23:00","notes":"2 courts also lined for pickleball"}}'::jsonb where slug = 'parc-duval-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/parc-george-springate","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Park 6:00-23:00","notes":"No dedicated tennis page; listed as Centre sportif George Springate on borough page"}}'::jsonb where slug = 'parc-george-springate-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-greendale","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Daily 8:00-23:00","notes":"1 court also lined for pickleball"}}'::jsonb where slug = 'parc-greendale-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-grier","page_en":"https://montreal.ca/en/places/grier-park-tennis-courts","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Daily 8:00-23:00"}}'::jsonb where slug = 'parc-grier-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-parkinson","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Daily 8:00-23:00","notes":"Courts also lined for pickleball"}}'::jsonb where slug = 'parc-parkinson-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/parc-hillcrest","page_en":"https://montreal.ca/en/places/parc-hillcrest-outdoor-tennis-courts","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Daily 8:00-23:00"}}'::jsonb where slug = 'parc-hillcrest-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/court-de-tennis-du-parc-munro","page_en":"https://montreal.ca/en/places/parc-munro-outdoor-tennis-courts","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Daily 8:00-23:00","notes":"Borough is Pierrefonds-Roxboro per montreal.ca"}}'::jsonb where slug = 'parc-munro-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Pierrefonds-Roxboro","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-aragon","booking":"Free, no reservation, first-come-first-served; max 30 min singles / 60 min doubles","fees":"Free","season":"Daily 8:00-23:00","notes":"Borough is Pierrefonds-Roxboro per montreal.ca"}}'::jsonb where slug = 'parc-aragon-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"L''Ile-Bizard-Sainte-Genevieve","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-eugene-dostie","booking":"Courts 1-6 managed by Club de tennis de l''Ile-Bizard (membership); courts 7-8 open to the public, free","fees":"Public courts free; club membership fees not published","season":"Daily 7:00-23:00"}}'::jsonb where slug = 'parc-eugene-dostie-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"L''Ile-Bizard-Sainte-Genevieve","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/parc-jonathan-wilson","page_en":"https://montreal.ca/en/places/parc-jonathan-wilson","booking":"Free but mandatory online reservation via loisirs.montreal.ca, up to 72h ahead, valid Montreal library card (news regime since Jun 20)","fees":"Free","season":"Park 6:00-23:00","notes":"Pickleball allowed only until 20:00 (noise mitigation)"}}'::jsonb where slug = 'parc-jonathan-wilson-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Leonard","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-coubertin","page_en":"https://montreal.ca/en/places/parc-coubertin-outdoor-tennis-courts","booking":"Loisirs Montreal online mandatory, register 24h ahead for next day","fees":"Free (no fee stated)","season":"May 15 - Oct 30, daily 8:00-23:00"}}'::jsonb where slug = 'parc-coubertin-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Leonard","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-delorme","page_en":"https://montreal.ca/en/places/parc-delorme-tennis-courts","phone":"514 322-4605","booking":"Members only; sign-up with SOGEP attendant at park pavilion (Acces Saint-Leonard card or ID); members receive a key; not on Loisirs Montreal","fees":"Membership required; price not published","season":"May 15 - Oct 30, daily 8:00-23:00","operator":"SOGEP"}}'::jsonb where slug = 'parc-delorme-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Leonard","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-ferland","page_en":"https://montreal.ca/en/places/parc-ferland-outdoor-tennis-courts","booking":"Loisirs Montreal online mandatory, register 24h ahead for next day","fees":"Free (no fee stated)","season":"May 15 - Oct 30, daily 8:00-23:00"}}'::jsonb where slug = 'parc-ferland-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Leonard","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-hebert","page_en":"https://montreal.ca/en/places/parc-hebert-outdoor-tennis-courts","booking":"Loisirs Montreal online mandatory, register 24h ahead for next day","fees":"Free (no fee stated)","season":"May 15 - Oct 30, daily 8:00-23:00"}}'::jsonb where slug = 'parc-hebert-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Leonard","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-ladauversiere","page_en":"https://montreal.ca/en/places/parc-ladauversiere-outdoor-tennis-courts","booking":"Loisirs Montreal online mandatory, register 24h ahead for next day","fees":"Free (no fee stated)","season":"May 15 - Oct 30, daily 8:00-23:00"}}'::jsonb where slug = 'parc-ladauversiere-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Leonard","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-luigi-pirandello","page_en":"https://montreal.ca/en/places/parc-luigi-pirandello-outdoor-tennis-courts","booking":"Loisirs Montreal online mandatory, register 24h ahead for next day","fees":"Free (no fee stated)","season":"May 15 - Oct 30, daily 8:00-23:00"}}'::jsonb where slug = 'parc-luigi-pirandello-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Leonard","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-pie-xii","page_en":"https://montreal.ca/en/places/parc-pie-xii-outdoor-tennis-courts","booking":"Loisirs Montreal online mandatory, register 24h ahead for next day","fees":"Free (no fee stated)","season":"May 15 - Oct 30, daily 8:00-23:00"}}'::jsonb where slug = 'parc-pie-xii-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Saint-Leonard","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-wilfrid-bastien","page_en":"https://montreal.ca/en/places/parc-wilfrid-bastien-outdoor-tennis-courts","booking":"Loisirs Montreal online mandatory, register 24h ahead for next day","fees":"Free (no fee stated)","notes":"Temporarily closed, work ongoing (2026-07)"}}'::jsonb where slug = 'parc-wilfrid-bastien-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Anjou","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-des-roseraies","page_en":"https://montreal.ca/en/places/parc-des-roseraies-tennis-courts","email":"loisirs.anjou@montreal.ca","booking":"No reservation; magnetic access card required ($5 + $5 activation, 2026), hourly rotation on the hour; card sold at Centre communautaire d''Anjou","fees":"Card $5 + $5 activation; play free with card","season":"May 2 - Oct 12, daily 7:00-22:30","notes":"Tennis Montreal has priority on 2 of 4 courts during lessons"}}'::jsonb where slug = 'parc-des-roseraies-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Anjou","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-goncourt","page_en":"https://montreal.ca/en/places/parc-goncourt-tennis-courts","email":"loisirs.anjou@montreal.ca","booking":"No reservation; magnetic access card required ($5 + $5 activation, 2026), hourly rotation on the hour; card sold at Centre communautaire d''Anjou","fees":"Card $5 + $5 activation; play free with card","season":"May 2 - Oct 12, daily 7:00-22:30"}}'::jsonb where slug = 'parc-goncourt-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Anjou","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-lucie-bruneau","page_en":"https://montreal.ca/en/places/parc-lucie-bruneau-tennis-courts","email":"loisirs.anjou@montreal.ca","booking":"No reservation; magnetic access card required ($5 + $5 activation, 2026), hourly rotation on the hour; card sold at Centre communautaire d''Anjou","fees":"Card $5 + $5 activation; play free with card","season":"May 2 - Oct 12, daily 7:00-22:30"}}'::jsonb where slug = 'parc-lucie-bruneau-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Anjou","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-roger-rousseau","page_en":"https://montreal.ca/en/places/parc-roger-rousseau-tennis-courts","email":"loisirs.anjou@montreal.ca","booking":"No reservation; magnetic access card required ($5 + $5 activation, 2026), hourly rotation on the hour; card sold at Centre communautaire d''Anjou","fees":"Card $5 + $5 activation; play free with card","season":"May 2 - Oct 12, daily 7:00-22:30","notes":"Tennis Montreal has priority on 2 of 4 courts during lessons"}}'::jsonb where slug = 'parc-roger-rousseau-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Montreal-Nord","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennispickleball-tennis-leger-du-parc-le-carignan","page_en":"https://montreal.ca/en/places/parc-le-carignan-outdoor-tennis-courts","phone":"514 328-4000 ext 4267","booking":"Borough reservation office 514 328-4000 ext 4267; free-play windows published per park (May 25 - Nov 1, 2026)","fees":"$19/h per court rental; free during scheduled open-play windows","season":"Park 6:00-23:00, Apr 17 - Nov 5","notes":"Official page lists 2 shared tennis/pickleball courts"}}'::jsonb where slug = 'parc-le-carignan-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Montreal-Nord","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-et-de-pickleball-tennis-leger-du-parc-ottawa","page_en":"https://montreal.ca/en/places/parc-ottawa-outdoor-tennis-courts","email":"reservationsmtln@montreal.ca","booking":"Reserve by email; recognized borough organizations free; scheduled play windows May 25 - Nov 1","fees":"$19 per court for other renters","season":"Park 6:00-23:00, Apr 17 - Nov 5","notes":"Official page lists 2 shared tennis/pickleball courts"}}'::jsonb where slug = 'parc-ottawa-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Montreal-Nord","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-saint-laurent","page_en":"https://montreal.ca/en/places/parc-saint-laurent-outdoor-tennis-courts","phone":"514 328-4000 ext 4267","booking":"Borough reservation office 514 328-4000 ext 4267; free-play windows published per park (May 25 - Nov 1, 2026)","fees":"$19/h per court rental; free during scheduled open-play windows","season":"Park 6:00-23:00, Apr 17 - Nov 5"}}'::jsonb where slug = 'parc-saint-laurent-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Montreal-Nord","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-sauve","page_en":"https://montreal.ca/en/places/parc-sauve-outdoor-tennis-courts","booking":"Reservation required (borough office); open tennis May 25 - Nov 1: Mon-Fri 12:00-17:00, Sat-Sun 13:00-21:00","fees":"Paid rental (borough standard $19/h)","season":"Park 6:00-23:00, Apr 17 - Nov 5"}}'::jsonb where slug = 'parc-sauve-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Montreal-Nord","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-ecole-calixa-lavallee","page_en":"https://montreal.ca/en/places/parc-ecole-calixa-lavallee-outdoor-tennis-courts","phone":"514 328-4000 ext 4267","booking":"Borough reservation office 514 328-4000 ext 4267; free-play windows published per park (May 25 - Nov 1, 2026)","fees":"$19/h per court rental; free during scheduled open-play windows","season":"Park 6:00-23:00, Apr 17 - Nov 5","notes":"Schoolyard park; school use may take precedence"}}'::jsonb where slug = 'parc-ecole-calixa-lavallee-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Riviere-des-Prairies-Pointe-aux-Trembles","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-clementine-de-la-rousseliere","booking":"Free, no reservation (borough page updated 2026-06-08)","fees":"Free","season":"Daily 6:00-23:00"}}'::jsonb where slug = 'parc-clementine-de-la-rousseliere-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Riviere-des-Prairies-Pointe-aux-Trembles","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-daniel-johnson","booking":"Free, no reservation (borough page updated 2026-06-08)","fees":"Free","season":"Daily 6:00-23:00"}}'::jsonb where slug = 'parc-daniel-johnson-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Riviere-des-Prairies-Pointe-aux-Trembles","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-de-lecole-secondaire-de-la-pointe-aux-trembles","booking":"Free, no reservation (borough page updated 2026-06-08)","fees":"Free","season":"Daily 6:00-23:00"}}'::jsonb where slug = 'parc-de-l-ecole-secondaire-de-la-pointe-aux-trembles-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Riviere-des-Prairies-Pointe-aux-Trembles","checked_at":"2026-07-23","source":"official website","page_en":"https://montreal.ca/en/places/parc-dollard-morin-outdoor-tennis-courts","booking":"Free, no reservation (FR page: il n''est pas necessaire de reserver)","fees":"Free","season":"Daily 9:00-23:00"}}'::jsonb where slug = 'parc-dollard-morin-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Riviere-des-Prairies-Pointe-aux-Trembles","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/parc-marie-claire-daveluy","page_en":"https://montreal.ca/en/places/parc-marie-claire-daveluy","booking":"Free, no reservation (borough page updated 2026-06-08)","fees":"Free","season":"Park 6:00-23:00","notes":"No dedicated tennis page; general park page lists a tennis court"}}'::jsonb where slug = 'parc-marie-claire-daveluy-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Mercier-Hochelaga-Maisonneuve","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-et-de-pickleball-du-parc-louis-riel","page_en":"https://montreal.ca/en/places/parc-louis-riel-outdoor-tennis-courts","booking":"Free play first-come-first-served on courts 1-6, max 1h; courts 7-12 reservable only by borough-recognized organizations; no public online booking","fees":"Free","season":"From May 16: daily 9:00-22:20","notes":"Courts 1-2 convert to 4 pickleball courts Mon/Wed/Sat/Sun 15:15-20:00 with free equipment loan"}}'::jsonb where slug = 'parc-louis-riel-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Rosemont-La Petite-Patrie","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-beaubien","page_en":"https://montreal.ca/en/places/parc-beaubien-outdoor-tennis-courts","phone":"514 872-1142","booking":"Loisirs Montreal, phone or on-site kiosk; max 24h ahead (same/next day), >=1h before play; 60-min slots; max 2h; waitlist 10 min before the hour","fees":"$13.75 per 1h slot (public Loisirs Montreal price, 2026); free windows Mon-Fri 7-9 + 22-23, Sat-Sun 7-9 + 20-23","season":"Reservations from Apr 26, 2026","notes":"Pickleball priority slots weekday mornings"}}'::jsonb where slug = 'parc-beaubien-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Rosemont-La Petite-Patrie","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/parc-jean-duceppe","page_en":"https://montreal.ca/en/places/parc-jean-duceppe-outdoor-tennis-courts","booking":"Free, first-come-first-served, hourly rotation","fees":"Free","season":"Daily 7:00-22:30, from mid-April"}}'::jsonb where slug = 'parc-jean-duceppe-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Rosemont-La Petite-Patrie","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrain-de-tennis-du-parc-sainte-bernadette","booking":"Free, no reservation; fixed 60-min sessions on the hour","fees":"Free","season":"Daily 7:00-23:00"}}'::jsonb where slug = 'parc-sainte-bernadette-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Villeray-Saint-Michel-Parc-Extension","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-francois-perrault","notes":"PERMANENTLY CLOSED per montreal.ca (Ferme definitivement, due to court condition)"}}'::jsonb where slug = 'parc-francois-perrault-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Villeray-Saint-Michel-Parc-Extension","checked_at":"2026-07-23","source":"official website","page_en":"https://montreal.ca/en/places/parc-george-vernot-outdoor-tennis-courts","booking":"No reservation system in this borough","notes":"Closed for construction, summer 2026 (borough page)"}}'::jsonb where slug = 'parc-george-vernot-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Villeray-Saint-Michel-Parc-Extension","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-jarry-stade-iga","page_en":"https://montreal.ca/en/places/parc-jarry-tennis-courts-stade-iga","phone":"514 273-1234","email":"accueil@tenniscanada.com","booking":"Activity Messenger account required (activitymessenger.com/org/2904); Acces Montreal cardholders 3 days ahead from 20:30, others 2 days; 2h/day cap; cancellation >=24h full credit","fees":"Outdoor $10/h regular, $8 AM card, $3 AM junior, $5 AM senior; summer unlimited package $100/$50/$70","season":"Daily 7:00-23:00, seasonal; CLOSED Jul 20 - Aug 21, 2026 (National Bank Open)","operator":"Tennis Canada (Stade IGA)"}}'::jsonb where slug = 'parc-jarry-stade-iga-terrains-de-tennis-exterieurs-durs-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Villeray-Saint-Michel-Parc-Extension","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-jarry-stade-iga","page_en":"https://montreal.ca/en/places/parc-jarry-tennis-courts-stade-iga","phone":"514 273-1234","email":"accueil@tenniscanada.com","booking":"Activity Messenger; 1h/day cap Oct 2 - May 31, 2h/day Jun 1 - Oct 1","fees":"Oct 2 - May 31: $35/$30/$15/$25 per h; Jun 1 - Oct 1: $15 all","season":"Year-round 7:00-23:00; CLOSED Jul 13 - Aug 28, 2026 (National Bank Open)","operator":"Tennis Canada (Stade IGA)"}}'::jsonb where slug = 'parc-jarry-stade-iga-terrains-de-tennis-interieurs-durs-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Villeray-Saint-Michel-Parc-Extension","checked_at":"2026-07-23","source":"official website","page_fr":"https://montreal.ca/lieux/terrains-de-tennis-du-parc-jarry-stade-iga","page_en":"https://montreal.ca/en/places/parc-jarry-tennis-courts-stade-iga","phone":"514 273-1234","email":"accueil@tenniscanada.com","booking":"Activity Messenger; same caps as indoor hard","fees":"Oct 2 - May 31: $40/$35/$20/$30 per h; Jun 1 - Oct 1: $20 all","season":"Daily 7:00-23:00; CLOSED Jul 13 - Sep 6, 2026 (National Bank Open)","notes":"4 covered rooftop clay courts; closed late 2025 for asbestos check, reopened Feb 2026","operator":"Tennis Canada (Stade IGA)"}}'::jsonb where slug = 'parc-jarry-stade-iga-terrains-de-tennis-interieurs-terre-battue-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Westmount (city)","checked_at":"2026-07-23","source":"official website","page_en":"https://westmount.org/en/leisure-and-community/sports-activities-and-facilities/outdoor-sports-facilities","phone":"514 989-5353","email":"recreation@westmount.org","booking":"No reservation, first-come-first-served, 1h max with rotation on the hour; Westmount Facility Access Card (residents) or guest pass required","fees":"Access card $65/yr individual, $50 senior, $130 family; guest pass $8 hard / $10 clay (members'' guests only)","season":"April to November, courts 7:00-22:00","operator":"City of Westmount"}}'::jsonb where slug = 'parc-devon-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Westmount (city)","checked_at":"2026-07-23","source":"official website","page_en":"https://westmount.org/en/leisure-and-community/sports-activities-and-facilities/outdoor-sports-facilities","phone":"514 989-5353","email":"recreation@westmount.org","booking":"No reservation, first-come-first-served, 1h max with rotation on the hour; Westmount Facility Access Card (residents) or guest pass required; guests cannot use clay without a resident member","fees":"Access card $65/yr individual, $50 senior, $130 family; guest pass $8 hard / $10 clay (members'' guests only)","season":"April to November, courts 7:00-22:00","notes":"King George Park (Murray Hill): 2 clay + 2 hard","operator":"City of Westmount"}}'::jsonb where slug = 'parc-king-george-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Westmount (city)","checked_at":"2026-07-23","source":"official website","page_en":"https://westmount.org/en/leisure-and-community/sports-activities-and-facilities/outdoor-sports-facilities","phone":"514 989-5353","email":"recreation@westmount.org","booking":"No reservation, first-come-first-served, 1h max with rotation on the hour; Westmount Facility Access Card (residents) or guest pass required","fees":"Access card $65/yr individual, $50 senior, $130 family; guest pass $8 hard / $10 clay (members'' guests only)","season":"April to November, courts 7:00-22:00","operator":"City of Westmount"}}'::jsonb where slug = 'parc-stayner-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Westmount (city)","checked_at":"2026-07-23","source":"official website","page_en":"https://westmount.org/en/leisure-and-community/sports-activities-and-facilities/outdoor-sports-facilities","phone":"514 989-5353","email":"recreation@westmount.org","booking":"No reservation, first-come-first-served, 1h max with rotation on the hour; Westmount Facility Access Card (residents) or guest pass required","fees":"Access card $65/yr individual, $50 senior, $130 family; guest pass $8 hard / $10 clay (members'' guests only)","season":"April to November, courts 7:00-22:00","notes":"4 clay + 2 hard tennis + 2 pickleball; WRC lessons have priority","operator":"City of Westmount"}}'::jsonb where slug = 'parc-westmount-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Westmount (city)","checked_at":"2026-07-23","source":"official website","page_en":"https://westmount.org/en/leisure-and-community/sports-activities-and-facilities/outdoor-sports-facilities","phone":"514 989-5353","email":"recreation@westmount.org","booking":"No reservation, first-come-first-served, 1h max with rotation on the hour; Westmount Facility Access Card (residents) or guest pass required","fees":"Access card $65/yr individual, $50 senior, $130 family; guest pass $8 hard / $10 clay (members'' guests only)","season":"April to November, courts 7:00-22:00","operator":"City of Westmount"}}'::jsonb where slug = 'terrains-de-tennis-du-terrain-d-athletisme-de-westmount-wag-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Hampstead (town)","checked_at":"2026-07-23","source":"official website","page_fr":"https://www.hampstead.qc.ca/fr/loisirs/programmation-et-inscription/tennis/","page_en":"https://www.hampstead.qc.ca/en/recreation/programming-and-registration/tennis/","phone":"438 872-4605 (tennis line)","booking":"Online via Mon.Hampstead, max 1 week ahead, 4 active reservations; priority windows Tue 9:00 (residents) / Wed 9:00 (CSL club members); 15-min no-show forfeit","fees":"2026 season passes: family $720/$925, individual $490/$755, senior $335/$425, student $285/$425, junior $125/$195; guest $25/$35","season":"Opened May 17, 2026","operator":"Town of Hampstead"}}'::jsonb where slug = 'parc-hampstead-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Cote Saint-Luc (city)","checked_at":"2026-07-23","source":"official website","page_fr":"https://cotesaintluc.org/fr/lieu/terrains-de-tennis-et-de-pickleball-caldwell/","page_en":"https://cotesaintluc.org/en/place/caldwell-tennis-and-pickleball-courts/","phone":"514 485-6806","email":"recreation@cotesaintluc.org","booking":"No reservation; free play, CSL residents only; no attendant","fees":"Free","season":"Mid-May to mid-October, daily 9:00-22:00","notes":"5 hardcourts, 2 dual-lined for pickleball per official page","operator":"City of Cote Saint-Luc"}}'::jsonb where slug = 'parc-caldwell-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Cote Saint-Luc (city)","checked_at":"2026-07-23","source":"official website","page_fr":"https://cotesaintluc.org/fr/lieu/parc-rembrandt/","page_en":"https://cotesaintluc.org/en/place/rembrandt-park/","phone":"514 485-6806","email":"service@cotesaintluc.org","booking":"Reservation required with CSL Fun Card via Amilia (cotesaintluc.org/amilia) or OPEN app; up to 7 days ahead; 1 slot/day; cancel >=2h","fees":"Free for Fun Card holders","season":"Mid-May to mid-October, daily 7:00-23:00","operator":"City of Cote Saint-Luc"}}'::jsonb where slug = 'parc-rembrandt-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Dorval (city)","checked_at":"2026-07-23","source":"official website","page_fr":"https://www.tennisdorval.org","page_en":"https://www.ville.dorval.qc.ca/en/leisure-and-culture/sport-and-leisure-activities/sports-facilities","phone":"514 631-6047","email":"lc@ville.dorval.qc.ca","booking":"Members-only club; season pass via Amilia; court booking via Balle Jaune (ballejaune.com/club/dorvaltennis); guests $15, max 4/season, with a member","fees":"Membership priced in the Amilia store; unlimited clay access for members","season":"Early May to mid-October","notes":"8 clay courts; no pickleball at the club per official pages","operator":"Club Municipal de Tennis de Dorval / City of Dorval"}}'::jsonb where slug = 'club-municipal-de-tennis-de-dorval-montreal';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Dollard-des-Ormeaux (city)","checked_at":"2026-07-23","source":"official website","page_fr":"https://ville.ddo.qc.ca/ma-municipalite/installations/parcs-et-terrains-de-jeux","page_en":"https://ville.ddo.qc.ca/en/play/sports-and-leisure/parks-and-playgrounds/","phone":"514 684-1010","email":"ville@ddo.qc.ca","booking":"No reservation, first-come-first-served, 1h courtesy limit; DDO residents only (by-law 80-672)","fees":"Free","season":"Play 8:00-22:00","operator":"City of Dollard-des-Ormeaux"}}'::jsonb where slug = 'coolbrooke-park-mooxhxwt';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Dollard-des-Ormeaux (city)","checked_at":"2026-07-23","source":"official website","page_fr":"https://ville.ddo.qc.ca/ma-municipalite/installations/parcs-et-terrains-de-jeux","page_en":"https://ville.ddo.qc.ca/en/play/sports-and-leisure/parks-and-playgrounds/","phone":"514 684-1010","email":"ville@ddo.qc.ca","booking":"No reservation, first-come-first-served, 1h courtesy limit; DDO residents only (by-law 80-672)","fees":"Free","season":"Play 8:00-22:00","operator":"City of Dollard-des-Ormeaux"}}'::jsonb where slug = 'parc-terry-fox-mooxtk4q';
update facility set attributes = coalesce(attributes, '{}'::jsonb) || '{"official_info":{"borough":"Dollard-des-Ormeaux (city)","checked_at":"2026-07-23","source":"official website","page_fr":"https://ville.ddo.qc.ca/ma-municipalite/installations/parcs-et-terrains-de-jeux","page_en":"https://ville.ddo.qc.ca/en/play/sports-and-leisure/parks-and-playgrounds/","phone":"514 684-1010","email":"ville@ddo.qc.ca","booking":"No reservation, first-come-first-served, 1h courtesy limit; DDO residents only (by-law 80-672)","fees":"Free","season":"Play 8:00-22:00","operator":"City of Dollard-des-Ormeaux"}}'::jsonb where slug = 'parc-westwood-mooy2bm5';

-- 6. Organization contact info --------------------------------------------------
update organization set website = coalesce(website, 'https://montreal.ca'), phone = coalesce(phone, '514-872-0311')
  where name = 'Ville de Montreal';
